version: '3'

services:
  reviews:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  seed:
    build: ./database
    depends_on:
      - 'database'

  database:
    image: myql:8.0.13-1.1.8
