version: '3'

services:
  reviews:
    build: .
    restart: always
    depends_on:
      - 'database'
    volumes: 
      - ./:/src/app
    ports: 
      - '3003:3003'

  database:
    build: ./database
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'reviewsDB'
      NYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    
